import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthProvider";
import ReactQueryProvider from "@/lib/QueryClientProvider";
import { CartProvider } from "@/hooks/useCart";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KinboBD",
  description: "Generated by create next app",
};
export type TChildren = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: TChildren) {
  return (
    <html lang="en" data-theme="light" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <AuthProvider>
            <CartProvider>{children}</CartProvider>
            
             {/* {children} */}
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
